version: '3.8'
services:
  ipam-ui-dev:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
      args:
        PORT: 8080
    environment:
      VITE_AZURE_ENV: ${AZURE_ENV}
      VITE_UI_ID: ${UI_APP_ID}
      VITE_ENGINE_ID: ${ENGINE_APP_ID}
      VITE_TENANT_ID: ${TENANT_ID}
      WDS_SOCKET_PORT: 3000
    volumes:
      - ./ui:/app
      - /app/node_modules
    networks:
      my-network-name:
        aliases:
          - ipam-ui-name
  ipam-engine-dev:
    build:
      context: ./engine
      dockerfile: Dockerfile.dev
      args:
        PORT: 8080
    environment:
      CLIENT_ID: ${ENGINE_APP_ID}
      CLIENT_SECRET: ${ENGINE_APP_SECRET}
      TENANT_ID: ${TENANT_ID}
      COSMOS_URL: ${COSMOS_URL}
      COSMOS_KEY: ${COSMOS_KEY}
      KEYVAULT_URL: ${KEYVAULT_URL}
    volumes:
      - ./engine/app:/code/app
    networks:
      my-network-name:
        aliases:
          - ipam-engine-name
  nginx-proxy-dev:
    depends_on:
      - ipam-ui-dev
      - ipam-engine-dev
    build:
      context: ./lb
      dockerfile: Dockerfile.dev
    networks:
      my-network-name:
        aliases:
          - proxy-name
    ports:
      - "3000:8080"
networks:
  my-network-name:
